# Q1. ax, Autograd and Neural Networks (40 points + 14 Bonus points)

## (a) Univariate Function Gradient (5 points)

In [2]:
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random
import numpy as np

# Q1a.  Example for taking the derivative of a simple function

def fun(x):
    return jnp.cos(x**3 - 2*x**2 + 5)

def manual_grad(x):
    # Implement the derivative w.r.t. x
    # ==================YOUR CODE HERE =================
    gradient=-(3*x**2 - 4*x)*jnp.sin(x**3 - 2*x**2 + 5)
    # ==================================================
    return gradient

grad_fun = grad(fun)

x = 3.5

print("Gradient:", grad_fun(x),  manual_grad(x))


Gradient: 22.353619 22.353619


## (b) Multivariate Function Gradient (5 points)

In [ ]:
# Now let's do it for a multivariate case

#Q1b.  Please complete the manual grad.


def cubic_l2_norm(x):
    return jnp.linalg.norm(x)**3

# Now complete the following line
grad_fun = grad(cubic_l2_norm)


x = jnp.array([5.0,0.3,2])

def manual_grad(x):
    # Manually implement the gradient w.r.t. x
    # ==================YOUR CODE HERE =================
    gradient = 3 * jnp.linalg.norm(x)**2 * x
    # ==================================================
    return gradient

print("Gradient:", grad_fun(x),  manual_grad(x))



Gradient: [80.902725  4.854164 32.36109 ] [-436.35004   -26.181002 -174.54001 ]


### Implement a function that computes the Hessian matrix for the given function (2 Bonus points)

In [ ]:
# Code for computing Hessian matrix


## (c) Soft-Max Regression and Neural Networks (15 points)

In [ ]:

# Q1c. Neural Network from Scratch
# Example implementation of simple soft-max regression with square loss
#[Nothing to implement in this block]

# define soft argmax
def soft_argmax(x):
    y = jnp.exp(x)
    return y/jnp.sum(y)

# Specify the how to caculate the

def predict(params, inputs):
    W = params[0]
    b = params[1]
    scores = jnp.dot( W, inputs) + b
    outputs = soft_argmax(scores)
    return outputs

def loss_fun(params, inputs, targets):
    preds = predict(params, inputs)
    # You can use cross-entropy loss instead
    return jnp.sum((preds - targets)**2)

grad_fun = grad(loss_fun)  # gradient evaluation function

# Lets' cook up some input for this
W = np.random.randn(3,4)
b = np.random.randn(3,1)
inputs = np.random.randn(4,1)
targets = np.array([1,0,0])
params=[W,b]



In [ ]:
# Example usage of above functions
# [Nothing to implement in this block]

# How to Generate a prediction for this inputs
print(predict(params, inputs))

# How to Compute the gradient from this imput
print(grad_fun(params, inputs,targets))

# How to implement an SGD udpate
# Take a minibatch of data X,y
def sgd_update(params,X,y):
    lr = 0.01
    gradient = grad_fun(params,X,y)
    for param, g in zip(params,gradients):
        param -= lr*g


[[0.03605837]
 [0.18608597]
 [0.77785563]]
[Array([[-0.32481027,  0.03874615, -0.06475117, -0.0412962 ],
       [-1.2605213 ,  0.15036577, -0.25128585, -0.16026199],
       [ 1.5853318 , -0.18911195,  0.3160371 ,  0.2015582 ]],      dtype=float32), Array([[-0.13087657],
       [-0.5079048 ],
       [ 0.6387815 ]], dtype=float32)]


**Now you are expected to implement a two-layer neural network from scratch by modifying the above code for soft-max regression.**

**Very Important the only function you need to modify is** `predict_nn`

In [ ]:
# Q1c.  continues

#  You may use jnp.tanh to implement a hyperbolic tangent activation fuonction.
#

def predict_nn(params, inputs):

    W1 = params[0]
    b1 = params[1]
    W2 = params[2]
    b2 = params[3]

    # ==================YOUR CODE HERE =================

    # implement the score function of a two layer neural networks.

    # ==================================================
    outputs = soft_argmax(scores)
    return outputs


def loss_fun_nn(params, inputs, targets):
    preds = predict_nn(params, inputs)
    # You can use logistic loss instead
    return jnp.sum((preds - targets)**2)

grad_fun_nn = grad(loss_fun_nn)  # gradient evaluation function

## (d) Neural Network Parameters and Gradient (15 points)
Now let's say the neural network is supposed to classify

In [ ]:
# Q1d Lets' cook up some input:

inputs = np.random.randn(64,1)
targets = np.array([1,0,0])

# What could be a valid shape of the following parameters?  Replace the question marks with valid numbers

# ==================YOUR CODE HERE =================

W1 = np.random.randn(?,?)
b1 = np.random.randn(?,?)
W2 = np.random.randn(?,?)
b2 = np.random.randn(?,?)

 # ==================================================

# W1 = np.random.randn(6,2)
# b1 = np.random.randn(6,1)
# W2 = np.random.randn(3,6)
# b2 = np.random.randn(3,1)
params=[W1,b1,W2,b2]



In [ ]:
# Generate a prediction for this inputs
predict_nn(params, inputs)

# Compute the gradient from this imput
grad_fun_nn(params, inputs,targets)

[Array([[ 0.00309208,  0.02634501],
        [ 0.05308639,  0.45230433],
        [-0.09310891, -0.79330254],
        [-0.03095572, -0.2637476 ],
        [ 0.04543963,  0.38715276],
        [ 0.01311291,  0.11172401]], dtype=float32),
 Array([[-0.02114253],
        [-0.36298558],
        [ 0.6366452 ],
        [ 0.21166407],
        [-0.31069982],
        [-0.08966132]], dtype=float32),
 Array([[ 0.17251822, -0.11501967, -0.12219113, -0.09222406,  0.05304084,
          0.19924021],
        [-0.470095  ,  0.31341717,  0.33295867,  0.25130138, -0.14453101,
         -0.54290974],
        [ 0.2975768 , -0.19839753, -0.21076758, -0.15907736,  0.09149019,
          0.3436696 ]], dtype=float32),
 Array([[-0.22494145],
        [ 0.61294305],
        [-0.38800168]], dtype=float32)]